working product page :sparkles:
PrzemekChociaj/music-shop pull request #22
Opened 2023-04-06 16:56 UTC by PrzemekChociaj

2023-04-09 16:47 UTC, qbawalat approved these changes

2023-04-09 16:47 UTC, qbawalat commented on src/App.tsx
> +			<Route path='Genres/HipHop' element={<HipHopPage />}></Route>
Zobacz, ze Genres jest powtarzajacym sie prefixem, warto go wyniesc do zmiennej, ze wzgledu latwiejsze zarzadzanie pathami, gdybys chcial je zmienic, czy ich kontrolowanie

2023-04-09 16:47 UTC, qbawalat commented on src/DataBase/WholeDatabase.tsx
> +export const SHOP_PRODUCTS = [
A moze zespoic (zaimportowac i stworzyc z nich jeden wielki json) w tym pliku reszte JSONOW zamiast je duplikowac? (PopData, RockData)

2023-04-09 16:47 UTC, qbawalat commented on src/components/Categories/ListDividers.tsx
> +		navigate('Genres/HipHop');
widzisz, tutaj tez sie powtarza genres. Przykladowo, gdybys kiedys musial to zmienic na "genres" musialbys wykonac zmiane we wszystkich plikach

2023-04-09 16:47 UTC, qbawalat commented on src/components/Pages/ExamplePage.tsx
> +	const obiekt = SHOP_PRODUCTS.find((product) => {
zangielszcz nazwe, nazwij pod wzgledem odpowiedzialnosci stalej

2023-04-09 16:47 UTC, qbawalat commented on src/components/Pages/ExamplePage.tsx
> +	}
Zamiast brak obiektu pokaz tu jakis przyjazny napis ;D

2023-04-12 16:43 UTC, khali16 requested changes

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/CartItem.tsx
> +const CartItem = ( {id, quantity}: CartItemProps) => {
I personally prefer to type components like this: 
 `const CartItem: FC<CartItemProps> = ({id, quantity}) => {}`

It is now clear that this is a component (FC-functional component), not a function that would take props as arguments

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/CartItem.tsx
> +    if (item == null) return null
Why not if(!item) retur null?

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/CartItem.tsx
> +<img src={item.img} style={{width: "125px", height: "75px", objectFit: "cover"}} />
Inline styles 👿

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/ShoppingCartContext.tsx
It's better to keep contexts in seperate folder e.g. in src/contexts

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/ShoppingCartContext.tsx
> +			if (currCds.find((item) => item.id === id) == null) {
It's good practice to take such logic to a separate function whose name will indicate what it does

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/ShoppingCartContext.tsx
> +			if (currCds.find((item) => item.id === id)?.quantity == 1) {
Same as above

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/ShoppingCartContext.tsx
> +	const getItemQuantity = (id: number) => {
You don't need braces and return statement here. Remeber that arrow function can return expected value right after an arrow:
`const getItemQuantity = (id: number) => musicCds.find((item) => item.id === id)?.quantity || 0`

2023-04-12 16:43 UTC, khali16 commented on src/components/ShoppingCart/ShoppingCartContext.tsx
> +	const removeFromCart = (id: number) => {
same as above

2023-04-17 13:04 UTC, merged